# Generated by Django 4.1.2 on 2022-11-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecard',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='image',
            field=models.ImageField(upload_to='home_card_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
