# Generated by Django 4.1.2 on 2022-11-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homecard_description_alter_homecard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/static/home_slide_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Home Slide',
                'verbose_name_plural': 'Home Slides',
            },
        ),
        migrations.AlterModelOptions(
            name='homecard',
            options={'verbose_name': 'Home Card', 'verbose_name_plural': 'Home Cards'},
        ),
        migrations.AlterField(
            model_name='homecard',
            name='image',
            field=models.ImageField(upload_to='home/static/home_card_images/', verbose_name='Image'),
        ),
    ]
