# Generated by Django 4.1.2 on 2022-11-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeslide_alter_homecard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
